name: Sync Obsidian to Hugo

on:
  schedule:
    - cron: '0 20 * * *'  # UTC 20:00 (北京时间次日4:00)
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Hugo Blog
        uses: actions/checkout@v4
        with:
          repository: cheparity/FluxBasalt
          token: ${{ secrets.GITHUB_TOKEN }}
          path: hugo-blog

      - name: Checkout Obsidian Vault
        uses: actions/checkout@v4
        with:
          repository: cheparity/MirrorBasalt
          token: ${{ secrets.PERSONAL_TOKEN }}  # 需要创建有 repo 权限的 PAT
          path: obsidian-vault

      - name: Install uv
        uses: astral-sh/setup-uv@v6

      - name: Install Hugo
        uses: peaceiris/actions-hugo@v2

      - name: Run publish script
        run: |
          cd hugo-blog
          uv run --no-project --with python-frontmatter ./scripts/publish.py \
            --content ./content \
            --vault ../obsidian-vault/MindHub

      - name: Build Hugo Site
        run: |
          cd hugo-blog
          hugo --minify

      - name: Commit and Push Changes
        run: |
          cd hugo-blog
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add .
          git commit -m "Auto-sync from Obsidian [skip ci]" || echo "No changes to commit"
          git push